# -*- coding: utf-8 -*-
"""Sepsis Dashboard V1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a6Xx-jQ82IW49wBVQTD9w_Z_4VlSRaiC
"""

# Clinical Sepsis Analytics Dashboard (V1)
# =========================================

import kagglehub
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path


# =========================
# 1. Dataset Download
# =========================

dataset_path = kagglehub.dataset_download(
    "salikhussaini49/prediction-of-sepsis"
)

dataset_file = Path(dataset_path) / "Dataset.csv"

dataset_raw_df = pd.read_csv(dataset_file)


# =========================
# 2. Load dataset
# =========================
dataset_raw_df = pd.read_csv(
    "/root/.cache/kagglehub/datasets/salikhussaini49/prediction-of-sepsis/versions/2/Dataset.csv"
)

print("\nShape:", dataset_raw_df.shape)
print("\nColumns:", dataset_raw_df.columns.tolist())
print("\nPatients:", dataset_raw_df["Patient_ID"].nunique())


# =========================
# 3. Missing Values Analysis
# =========================
missing = dataset_raw_df.isnull().mean().sort_values(ascending=False)
print("\nTop Missing Values:\n", missing.head(15))


clinical_rel_col = [
    'HR', 'Temp', 'MAP', 'Resp',
    'Creatinine', 'Lactate', 'WBC',
    'Platelets', 'O2Sat'
]

good_cols = missing[missing < 0.9].index
final_cols = list(set(good_cols) | set(clinical_rel_col))

dataset_clean = dataset_raw_df[final_cols]


# =========================
# 4. Patient-level aggregation
# =========================
dataset_agg = dataset_clean.groupby("Patient_ID").agg({
    "HR": ["mean", "max"],
    "O2Sat": ["mean", "min"],
    "Temp": ["mean", "min", "max"],
    "MAP": ["mean", "min"],
    "Resp": ["mean", "max"],
    "Lactate": ["mean", "max"],
    "WBC": ["mean", "max"],
    "Creatinine": "max",
    "Age": "first",
    "Gender": "first",
    "SepsisLabel": "max"
})

# flatten columns
dataset_agg.columns = [
    f"{col[0]}_{col[1]}" if isinstance(col, tuple) else col
    for col in dataset_agg.columns
]

dataset_agg = dataset_agg.rename(columns={"SepsisLabel_max": "SepsisPatient"})


print("\nFinal dataset shape:", dataset_agg.shape)


# =========================
# 5. Boxplots (clinical differences)
# =========================
features_to_plot = [
    ("HR_mean", "Heart Rate (beats per minute)"),
    ("MAP_mean", "Mean Arterial Pressure (mmHg)"),
    ("Lactate_max", "Lactic acid (mg/dL)"),
    ("Creatinine_max", "Creatinine (mg/dL)")
]

import os
os.makedirs("figures", exist_ok=True)

for feature, label in features_to_plot:
    plt.figure()
    sns.boxplot(data=dataset_agg, x="SepsisPatient", y=feature)
    plt.title(f"{label}: Sepsis vs Non-Sepsis")
    plt.xlabel("Sepsis Status (0 = No, 1 = Yes)")
    plt.ylabel(label)
    plt.savefig("figures/boxplot_" + feature + ".png", dpi=300, bbox_inches="tight")
    plt.show()


# =========================
# 6. Summary Table
# =========================
features = ["HR_mean", "MAP_mean", "Lactate_max", "Creatinine_max"]

comparison_df = pd.DataFrame({
    "Non_Sepsis": dataset_agg[dataset_agg["SepsisPatient"] == 0][features].mean(),
    "Sepsis": dataset_agg[dataset_agg["SepsisPatient"] == 1][features].mean()
})

print("\n=== Clinical Summary Table ===\n")
print(comparison_df.round(2))


# =========================
# 7. Final Heatmap
# =========================
plt.figure(figsize=(8, 5))

sns.heatmap(
    comparison_df,
    annot=True,
    cmap="Reds",
    fmt=".2f",
    linewidths=0.5
)

plt.title("Clinical Profile: Sepsis vs Non-Sepsis")
plt.ylabel("Clinical Parameters")
plt.xlabel("Group")
plt.savefig("figures/heatmap.png", dpi=300, bbox_inches="tight")
plt.show()

# =========================
# Simple Clinical Dashboard (V1 Summary View)
# =========================

def run_dashboard(dataset_agg):

    print("\n===== SEPSIS ANALYTICS DASHBOARD (V1) =====\n")

    # 1. Dataset Overview
    print("Dataset Shape:", dataset_agg.shape)
    print("\nSepsis Distribution:")
    print(dataset_agg["SepsisPatient"].value_counts(normalize=True).round(3))

    # 2. Key Clinical Summary
    features = ["HR_mean", "MAP_mean", "Lactate_max", "Creatinine_max"]

    summary = dataset_agg.groupby("SepsisPatient")[features].mean().T
    summary.columns = ["Non-Sepsis", "Sepsis"]

    print("\nClinical Summary (Mean Values):\n")
    print(summary.round(2))

    # 3. Quick Visualization
    plt.figure(figsize=(8, 5))
    sns.heatmap(summary, annot=True, cmap="Reds", fmt=".2f")
    plt.title("Sepsis vs Non-Sepsis Clinical Profile (V1)")
    plt.tight_layout()
    plt.show()


# Run dashboard
run_dashboard(dataset_agg)

